# Generated by Django 2.2.11 on 2020-03-21 17:08

from django.db import migrations, models
import services.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to=services.utils.photo_upload_to)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon ID. https://fontawesome.com/icons', max_length=255)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('short_description', models.TextField()),
            ],
            options={
                'ordering': ['order'],
                'index_together': {('is_active', 'order'), ('is_active', 'is_featured', 'order')},
            },
        ),
    ]
