# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20171125_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=None, upload_to='posts'),
            preserve_default=False,
        ),
    ]
