# Generated by Django 2.2.11 on 2020-03-22 12:25

from django.db import migrations, models
import projects.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('thumbnail', models.ImageField(blank=True, upload_to=projects.utils.photo_upload_to)),
                ('photo', models.ImageField(blank=True, upload_to=projects.utils.photo_upload_to)),
                ('color', models.CharField(help_text='CSS RGB code', max_length=6)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
                'index_together': {('is_active', 'is_featured', 'order'), ('is_active', 'order')},
            },
        ),
    ]
